### PR TITLE
Bump to 1.10.1

### PR DESCRIPTION
**Pull request by indutny**
As requested! ❤️

### CODE REVIEW

**Comment by indutny-signal** [comment]
Let's wait on merging this! Looks like @jrose-signal has one more PR! :)

**Comment by indutny-signal** [comment]
In the light of [@jrose-signal's comment](https://github.com/unicode-rs/unicode-segmentation/pull/112#issuecomment-1409590652), we are good to go! Thanks for giving us time to investigate!

**Comment by indutny** [comment]
(FWIW, above was my work account)

**Comment by indutny** [comment]
Thank you so much! :heart:

**Pull request merged**
