### PR TITLE
Upgrade to Unicode 10

### PR DESCRIPTION
**Pull request by rth**
Partially addresses https://github.com/unicode-rs/unicode-segmentation/issues/43 by first upgrading to Unicode 10.0 (from 9.0).

As mentioned in that issue,
> We may want to update to Unicode 10 before that; that should be a straightforward regen of the tables IIRC.

which is what I have done here.

From http://www.unicode.org/versions/Unicode10.0.0/ release notes,

> UAX # 29 Unicode Text Segmentation
>
> Strengthened the recommendation to use tailorings based on CLDR rules and emoji properties, for improved segmentation behavior of emoji zwj sequences. Changed the derivation of the Word_Break property value ALetter to include a set of 35 phonetic modifiers, to prevent word boundaries between those characters and alphabetic letters.

So no code changes are necessary as these modifications are included in the updated tables data, if I understand it right ?

### CODE REVIEW

**Comment by Manishearth** [comment]
Generates locally too.

Thanks!

Would you like to look into upgrading to Unicode 11? 12 is a simple data upgrade from there.

**Comment by rth** [comment]
> Would you like to look into upgrading to Unicode 11?

I might look into it at some point in the future, but probably not right now. That why I thought that upgrading to 10.0 could be a start..

**Comment by Manishearth** [comment]
Oops forgot to merge this

Thanks!

**Comment by rth** [comment]
No worries, I forgot I made it. Thanks for reviewing!

**Pull request merged**
